
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS STATUSES;

CREATE TABLE USER(
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  hash VARCHAR(100) NOT NULL
);

CREATE TABLE STATUSES(
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  message VARCHAR(140) NOT NULL,
  user_name VARCHAR(100),
  publishDate DATETIME NOT NULL,
  client varchar(256)
);
