
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS STATUS;

CREATE TABLE USER (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  hash VARCHAR(100) NOT NULL
);

CREATE TABLE STATUS (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  message VARCHAR(140) NOT NULL,
  userName VARCHAR(100) NOT NULL,
  publishDate DATETIME NOT NULL,
  client varchar(256)
);
